CREATE TABLE NV_NOTICE(
   NOTICENUM BIGINT AUTO_INCREMENT PRIMARY KEY,
   NOTICEWRITER VARCHAR(1000) NOT NULL,
   NOTICETITLE VARCHAR(1000) NOT NULL,
   NOTICECONTENTS VARCHAR(4000) NOT NULL,
   NOTICEDATE DATETIME,
   READCOUNT BIGINT
);

NOTICENUM,NOTICEDATE,NOTICEWRITER,NOTICETITLE,READCOUNT,NOTICECONTENTS;

CREATE TABLE NV_NOTICE_FILE(
   SYSTEMNAME VARCHAR(255) primary key,
   ORGNAME VARCHAR(1000),
   NOTICENUM BIGINT,
   CONSTRAINT FILE_FK1 FOREIGN KEY(NOTICENUM) REFERENCES NV_NOTICE(NOTICENUM)
);



SELECT * FROM nv_notice ORDER BY NOTICENUM DESC;
SELECT * FROM nv_notice_file ORDER BY NOTICENUM DESC;

select R1.* FROM (SELECT * FROM NV_NOTICE) R1 ORDER BY NOTICENUM desc LIMIT 10 OFFSET 0;

SELECT * FROM NV_NOTICE WHERE NOTICENUM>0 
	ORDER BY NOTICENUM DESC LIMIT 10 OFFSET 0;

SELECT * FROM NV_NOTICE WHERE NOTICENUM>0 
	ORDER BY NOTICENUM DESC LIMIT 0, 10;
			
DELETE FROM nv_notice WHERE NOTICENUM=123;

DELETE FROM nv_notice_file WHERE NOTICENUM IS NULL;

SELECT COUNT(*) FROM NV_NOTICE WHERE NOTICENUM>0;

INSERT INTO NV_NOTICE VALUES(NULL,'test','test','test',now(),1);

/*================================================================*/
DROP TABLE NV_NOTICE_IMG;

CREATE TABLE NV_NOTICE_IMG(
   SYSTEMNAME VARCHAR(255) primary key,
   ORGNAME VARCHAR(1000),
   NOTICENUM BIGINT,
   CONSTRAINT NOTICE_IMG_FK FOREIGN KEY(NOTICENUM) REFERENCES NV_NOTICE(NOTICENUM)
);

INSERT INTO NV_NOTICE_IMG(SYSTEMNAME,ORGNAME) VALUES
        ('asdas','asdasdasczx');

SELECT * FROM NV_NOTICE_IMG;

SELECT * FROM NV_NOTICE_IMG WHERE NOTICENUM IS NULL;
SELECT SYSTEMNAME FROM NV_NOTICE_IMG WHERE NOTICENUM IS NULL;

DELETE FROM NV_NOTICE_IMG;
DELETE FROM NV_NOTICE_IMG WHERE NOTICENUM IS NULL;