CREATE TABLE NV_NOTICE(
   NOTICENUM BIGINT AUTO_INCREMENT PRIMARY KEY,
   NOTICEWRITER VARCHAR(1000) NOT NULL,
   NOTICETITLE VARCHAR(1000) NOT NULL,
   NOTICECONTENTS VARCHAR(4000) NOT NULL,
   NOTICEDATE DATETIME,
   READCOUNT BIGINT
);

CREATE TABLE NV_NOTICE_FILE(
   SYSTEMNAME VARCHAR(255) primary key,
   ORGNAME VARCHAR(1000),
   NOTICENUM BIGINT,
   CONSTRAINT FILE_FK1 FOREIGN KEY(NOTICENUM) REFERENCES NV_NOTICE(NOTICENUM)
);
