
CREATE TABLE NV_ADMIN(
	ADMIN_ID VARCHAR(255) PRIMARY KEY,
	ADMIN_PW VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255),
	REG_DATE DATETIME DEFAULT now()
);

INSERT INTO NV_ADMIN(ADMIN_ID,ADMIN_PW,EMAIL) VALUES('admin2','admin1234','');
SELECT * FROM nv_admin;