/*관리자 테이블*/
CREATE TABLE NV_ADMIN(
	ID VARCHAR(255) PRIMARY KEY,
	PASSWORD VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255),
	PHONE VARCHAR(20),
	ROLE VARCHAR(20),
	REG_DATE DATETIME DEFAULT now()
);

/*테이블 조회*/
SELECT * FROM nv_admin;

DROP TABLE NV_ADMIN;
DROP TABLE ACCOUNT;
/*-------------------------------------------------------------------------------*/

INSERT INTO NV_ADMIN(ADMIN_ID,ADMIN_PW,EMAIL) VALUES('admin2','admin1234','');

SELECT ADMIN_ID FROM NV_ADMIN
        WHERE ADMIN_ID='admin2' AND ADMIN_PW='admin1234';

