show databases;
CREATE DATABASE newVisionEng;
use newVisionEng;


CREATE TABLE NV_NEWS(
	NEWSNUM BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NEWSTITLE VARCHAR(1000) NOT NULL,
	NEWSSUBTITLE VARCHAR(1000),
	NEWSLINK VARCHAR(1000),
   	NEWSWRITER VARCHAR(1000) NOT NULL,
   	NEWSCONTENTS VARCHAR(4000),
   	NEWSDATE VARCHAR(1000),
   	NEWSWRITEDATE DATETIME
   );
  
INSERT INTO NV_NEWS ( NEWSTITLE, NEWSSUBTITLE, NEWSLINK, NEWSWRITER, NEWSCONTENTS, NEWSDATE, NEWSWRITERDATE)
	VALUES("기사TEST TITLE", "기사TEST SUBTITLE", null, "기사TEST TESTER", "기사TEST CONTENTS", "기사TEST 2021-11-25", now());

INSERT INTO NV_NEWS ( NEWSTITLE, NEWSSUBTITLE, NEWSLINK, NEWSWRITER, NEWSCONTENTS, NEWSDATE, NEWSWRITERDATE)
	VALUES("기사TEST TITLE1", "기사TEST SUBTITLE1", "www.naver.com", "기사TEST TESTER1", "기사TEST CONTENTS1", "기사TEST 2021-11-26", now());

ALTER TABLE NV_NEWS CHANGE NEWSWRITERDATE NEWSWRITEDATE VARCHAR(1000); 
alter table article change user nickname varchar(30);
alter table article change user nickname varchar(30);

CREATE TABLE NV_NEWS_FILE(
   SYSTEMNAME VARCHAR(255) primary key,
   ORGNAME VARCHAR(1000),
   NEWSNUM BIGINT,
   CONSTRAINT NEWSFILE_FK1 FOREIGN KEY(NEWSNUM) REFERENCES NV_NEWS(NEWSNUM) ON DELETE CASCADE
);

  DROP TABLE NV_NEWS;
  DROP TABLE nv_news_file;
  TRUNCATE TABLE NV_NEWS; 
  TRUNCATE TABLE NV_NEWS_FILE;

  DELETE  FROM NV_NEWS WHERE NEWSNUM>5;
 
 DELETE  FROM NV_NEWS WHERE NEWSNUM = 18  
 
 ALTER TABLE order_items ADD FOREIGN KEY (item_id) REFERENCES orders (id) ON DELETE CASCADE;
 
  UPDATE NV_NEWS SET NEWSDATE = '2021-06-08' WHERE NEWSNUM = 6;
 
  SELECT * FROM nv_news;
  SELECT * FROM nv_news_file;
  
