show databases;
CREATE DATABASE newVisionEng;
use newVisionEng;


CREATE TABLE NV_NEWS(
	NEWSNUM BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   	NEWSWRITER VARCHAR(1000) NOT NULL,
   	NEWSTITLE VARCHAR(1000) NOT NULL,
   	NEWSCONTENTS VARCHAR(4000) NOT NULL,
   	NEWSDATE DATETIME,
   	READCOUNT BIGINT
   );

CREATE TABLE NV_NEWS_FILE(
   SYSTEMNAME VARCHAR(255) primary key,
   ORGNAME VARCHAR(1000),
   NEWSNUM BIGINT,
   CONSTRAINT NEWSFILE_FK1 FOREIGN KEY(NEWSNUM) REFERENCES NV_NEWS(NEWSNUM)
);

  DROP TABLE NV_NEWS;
  
  SELECT * FROM nv_news;
  SELECT * FROM nv_news_file;
  
 INSERT INTO NV_NEWS ( NEWSWRITER, NEWSTITLE, NEWSCONTENTS, NEWSDATE)
		VALUES( "TESTER3", "TEST3", "TEST3", now());