/*채용공고 테이블*/
CREATE TABLE NV_RECRUIT(
   RECRUITNUM BIGINT AUTO_INCREMENT PRIMARY KEY,
   RECRUITWRITER VARCHAR(1000) NOT NULL,
   RECRUITTITLE VARCHAR(1000) NOT NULL,
   RECRUITCONTENTS TEXT NOT NULL,
   RECRUITDATE DATETIME,
   READCOUNT BIGINT
);
/*채용공고 첨부파일 테이블*/
CREATE TABLE NV_RECRUIT_FILE(
   SYSTEMNAME VARCHAR(255) primary key,
   ORGNAME VARCHAR(1000),
   RECRUITNUM BIGINT,
   CONSTRAINT NV_RECRUIT_FILE_FK FOREIGN KEY(RECRUITNUM) 
   		REFERENCES NV_RECRUIT(RECRUITNUM) ON DELETE CASCADE
);
/*채용공고 내용에 삽입된 이미지 테이블*/
CREATE TABLE NV_RECRUIT_IMG(
   SYSTEMNAME VARCHAR(255) primary key,
   ORGNAME VARCHAR(1000),
   RECRUITNUM BIGINT,
   CONSTRAINT NV_RECRUIT_IMG_FK FOREIGN KEY(RECRUITNUM) 
   		REFERENCES NV_RECRUIT(RECRUITNUM) ON DELETE SET NULL
);

/*테이블 조회*/
SELECT * FROM NV_RECRUIT ORDER BY RECRUITNUM DESC;
SELECT * FROM NV_RECRUIT_FILE;
SELECT * FROM NV_RECRUIT_IMG;

/*테이블 드랍*/
DROP TABLE NV_RECRUIT;
DROP TABLE NV_RECRUIT_FILE;
DROP TABLE NV_RECRUIT_IMG;

/*더미 데이터 만들기 매우 편함 2의 배수씩 복제됨*/
INSERT INTO NV_RECRUIT(RECRUITTITLE,RECRUITWRITER,RECRUITCONTENTS,RECRUITDATE,READCOUNT)
 (SELECT RECRUITTITLE,RECRUITWRITER,RECRUITCONTENTS,RECRUITDATE,READCOUNT FROM NV_RECRUIT);
/*-------------------------------------------------------------------------------*/

INSERT INTO NV_RECRUIT VALUES(NULL,'tester','testTitle','testCONTENTS',now(),1);


  
DELETE FROM NV_RECRUIT WHERE RECRUITNUM > 0; 
 
ALTER TABLE NV_RECRUIT AUTO_INCREMENT=1;